---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/hadolint/hadolint
    rev: v2.4.0
    hooks:
      - id: hadolint
