version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout
      
      - setup_remote_docker

      - run:
          name: Install make
          command: |
            apk add --no-cache make

      - run:
          name: Build container
          command: |
            make build

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker-cloud
          filters:
            tags:
              only: /.*/
